# Generated by Django 3.1.7 on 2021-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioholdings',
            name='type',
            field=models.CharField(default='Buy', max_length=10),
        ),
    ]
