# Generated by Django 3.1.7 on 2021-03-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioholdings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioholdings',
            name='coin_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
