# Generated by Django 3.1.7 on 2021-03-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210320_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioholdings',
            name='coin_name',
            field=models.CharField(max_length=100),
        ),
    ]
