# Generated by Django 3.1.7 on 2021-03-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210320_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioholdings',
            name='amount_in_usd',
        ),
        migrations.AddField(
            model_name='portfolioholdings',
            name='coin_ticker',
            field=models.CharField(default='Your Ticker Here', max_length=100),
        ),
    ]
