# Generated by Django 3.1.7 on 2021-03-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210321_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioholdings',
            name='amount_in_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
